# Generated by Django 5.1 on 2024-08-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
