# Generated by Django 5.1 on 2024-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_registration_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
