# Generated by Django 5.1 on 2024-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_registration_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
