# Generated by Django 5.1 on 2024-08-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='photo',
            field=models.ImageField(upload_to='profile_picture/'),
        ),
    ]
